= Super Arm
:toc:

== Summary

This repository is for housing bootstrap scripts for Windows workstations 
(and now linuxs virtual machines via WSL 2).

Simply executing the ./bootstrap.bat file on a clean windows workstation should install all of the
desired packages.

This has only been used on Windows 10 workstations.

== Setup

Setup for fresh Windows workstation.

* Download zip -> unzip (via github console)
* Right click bat files of interest and run as administrator

=== SSH

Run the following commands as admin from command prompt.
Add public SSH key to github and anywhere else.

* `ssh-keygen -t rsa -b 4096`
** Hit enter when prompted to use no password and default location

=== WSL 2

Follow instruction https://docs.microsoft.com/en-us/windows/wsl/install-win10[here] for installing Windows Subsystem for Linux 2 (WSL 2)

Once complete, execute desired scripts under ./scripts/ws12/.

== Useful commands

* choco upgrade all -y
** Upgrade all installed packages
* choco list -l
** List all installed packages

== References

* Windows Packager Manager (Chocolatey)
** https://chocolatey.org